apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: semester4app
data:
  application.yml: |
    server:
      port: 8084
    
    spring:
      application:
        name: api-gateway
      cloud:
        gateway:
          routes:
            - id: user_service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=1
            - id: auth_service
              uri: lb://user-service
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=1
            - id: employee_service
              uri: lb://employee-service
              predicates:
                - Path=/api/employees/**
              filters:
                - StripPrefix=1
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,liveness,readiness
---

