apiVersion: v1
kind: Service
metadata:
  name: employee-service
  namespace: semester4app
spec:
  selector:
    app: employee-service
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP
---

